module.exports = {
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "@stylistic"],
  "rules": {
    "@stylistic/space-in-parens": ["error"],
    "@stylistic/comma-spacing": ["error"],
    "@stylistic/no-multi-spaces": ["error"],
    "@stylistic/no-trailing-spaces": ["error"],
    "@stylistic/no-whitespace-before-property": ["error"],
    "@stylistic/array-bracket-newline": ["error", "consistent"],
    "@stylistic/array-bracket-spacing": ["error"],
    "@stylistic/arrow-spacing": ["error"],
    "@stylistic/arrow-parens": ["error", "always"],
    "@stylistic/block-spacing": ["error", "always"],
    "@stylistic/brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "@stylistic/comma-dangle": ["error", "never"],
    "@stylistic/jsx-indent": ["error", 2],
    "@stylistic/key-spacing": ["error"],
    "@stylistic/keyword-spacing": ["error"],
    "@stylistic/member-delimiter-style": ["error", { "multiline": { "delimiter": "none" } }],
    "@stylistic/no-extra-semi": ["error"],
    "@stylistic/no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0, "maxBOF": 0 }],
    "@stylistic/object-curly-spacing": ["error", "always"],
    "@stylistic/padding-line-between-statements": [
      "error",
      { "blankLine": "always", "prev": "*", "next": ["export", "block", "interface"] },
      { "blankLine": "always", "prev": ["export", "block", "interface"], "next": "*" },
      { "blankLine": "any", "prev": "type", "next": "type" },
      { "blankLine": "never", "prev": "import", "next": "import" }
    ],
    "@stylistic/quotes": ["error", "single"],
    "@stylistic/semi": ["error", "never"],
    "@stylistic/space-before-blocks": ["error", "always"],
    "@stylistic/space-before-function-paren": ["error", { "anonymous": "never", "named": "never", "asyncArrow": "always" }],
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": "off",
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/consistent-type-assertions": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/no-angle-bracket-type-assertion": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-extra-non-null-assertion": "error",
    "@typescript-eslint/no-floating-promises": "off",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-misused-promises": "error",
    "@typescript-eslint/no-namespace": "off",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-object-literal-type-assertion": "off",
    "@typescript-eslint/no-parameter-properties": "off",
    "@typescript-eslint/no-shadow": "error",
    "@typescript-eslint/no-triple-slash-reference": "off",
    "@typescript-eslint/no-unused-vars": ["error", { "vars": "all", "args": "none", "varsIgnorePattern": "inject|(\\w+)Bindings", "ignoreRestSiblings": false }],
    "@typescript-eslint/no-use-before-define": "off",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-interface": "off",
    "@typescript-eslint/prefer-nullish-coalescing": "error",
    "@typescript-eslint/prefer-optional-chain": "error",
    "@typescript-eslint/return-await": "error",
    "@typescript-eslint/unified-signatures": "error"
  }
}
